# Site settings
title: "Erik ğŸ’Marian"
description: |
    #EriksOneInAMarian
owner: Erik Gaius Capistrano
first_published: 2020
email: gaius.coffee@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://erikandmarian.ph" # the base hostname & protocol for your site

# Google analytics
google_analytics: "UA-56797626-16"

social:
  github: https://github.com/gaiuscoffee/wedding-site
  twitter: https://twitter.com/gaiuscoffee
  facebook: https://facebook.com/gaiuscoffee
  linkedin: https://www.linkedin.com/in/gaiuscoffee
  link: https://gaius.coffee

# Build settings
markdown: kramdown
